package com.elitebnb_backend.entity;

public enum AuditActionType {
    USER_STATUS_UPDATED,
    PROPERTY_STATUS_UPDATED,
    BOOKING_STATUS_UPDATED,
    PAYMENT_STATUS_UPDATED,
    REPORT_STATUS_UPDATED,
    REPORT_MODERATION_ACTION,
    HOST_VERIFICATION_UPDATED,
    PROPERTY_APPROVAL_UPDATED,
    REFUND_STATUS_UPDATED,
    PLATFORM_SETTING_UPDATED
}
