apiVersion: v1
kind: Service
metadata:
  name: elitebnb-backend
  namespace: elitebnb
  labels:
    app.kubernetes.io/name: elitebnb-backend
    app.kubernetes.io/part-of: elitebnb
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: elitebnb-backend
  ports:
    - name: http
      port: 8086
      targetPort: http
      nodePort: 30086
