apiVersion: v1
kind: ConfigMap
metadata:
  name: elitebnb-backend-config
  namespace: elitebnb
  labels:
    app.kubernetes.io/name: elitebnb-backend
    app.kubernetes.io/part-of: elitebnb
data:
  SERVER_PORT: "8086"
  DB_URL: "jdbc:postgresql://elitebnb-postgres:5432/elitebnb"
  PAYSTACK_BASE_URL: "https://api.paystack.co"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "465"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE: "true"
  BREVO_API_URL: "https://api.brevo.com/v3/smtp/email"
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "10MB"
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "50MB"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_HEALTH_MAIL_ENABLED: "false"
  ELITEBNB_ADMIN_BOOTSTRAP_ENABLED: "false"
