apiVersion: v1
kind: Service
metadata:
  name: elitebnb-postgres
  namespace: elitebnb
  labels:
    app.kubernetes.io/name: elitebnb-postgres
    app.kubernetes.io/part-of: elitebnb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: elitebnb-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
