apiVersion: v1
kind: Secret
metadata:
  name: elitebnb-backend-secret
  namespace: elitebnb
  labels:
    app.kubernetes.io/name: elitebnb-backend
    app.kubernetes.io/part-of: elitebnb
type: Opaque
stringData:
  DB_USERNAME: CHANGE_ME
  DB_PASSWORD: CHANGE_ME
  PAYSTACK_SECRET_KEY: CHANGE_ME
  MAIL_USERNAME: CHANGE_ME
  MAIL_PASSWORD: CHANGE_ME
  BREVO_API_KEY: CHANGE_ME
  CLOUDINARY_CLOUD_NAME: CHANGE_ME
  CLOUDINARY_API_KEY: CHANGE_ME
  CLOUDINARY_API_SECRET: CHANGE_ME
  GOOGLE_CLIENT_ID: CHANGE_ME
  GOOGLE_CLIENT_SECRET: CHANGE_ME
  ELITEBNB_ADMIN_EMAIL: CHANGE_ME_OPTIONAL
  ELITEBNB_ADMIN_PASSWORD: CHANGE_ME_OPTIONAL
  ELITEBNB_ADMIN_FIRST_NAME: CHANGE_ME_OPTIONAL
  ELITEBNB_ADMIN_LAST_NAME: CHANGE_ME_OPTIONAL
